import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {normalizeListings} from './lib/listing-quality.mjs';
import {renderFilterBar,renderStatusTabs,renderGrids,patchIndex} from './update-listings.mjs';
import {buildListingPages} from './build-listing-pages.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const file=path.join(root,'data/listings.json');
const rows=normalizeListings(JSON.parse(await readFile(file,'utf8'))).map(l=>({...l,saleDate:l.saleDate?new Date(l.saleDate):null}));
const active=rows.filter(l=>!l.sold),sold=rows.filter(l=>l.sold);
const today=Date.parse(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'})+'T00:00:00Z');
const order=l=>l.saleDate && l.saleDate.getTime()>=today ? l.saleDate.getTime() : Number.MAX_SAFE_INTEGER;
active.sort((a,b)=>order(a)-order(b));
const index=path.join(root,'index.html');
const html=patchIndex(await readFile(index,'utf8'),{filterBar:renderFilterBar(rows),statusTabs:renderStatusTabs(active.length,sold.length),grids:renderGrids(active,sold),updatedLabel:new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric'})});
await writeFile(index,html);
await writeFile(file,JSON.stringify(rows,null,1));
await buildListingPages(root,rows);
console.log(`물건 ${rows.length}건, 확인된 낙찰 ${sold.length}건: 목록·상세 동기화`);
